### ISSUE TITLE
Please check regency and district

### ISSUE THREAD

**Issue by ndro-agus** [edwardsamuel/Wilayah-Administratif-Indonesia#10] opened 2016-10-27 12:33 UTC
i have imported all data from mysql file,
there are some district have no regency

check for ID 9419 until 9471, what is the regency name..?

**Comment by edwardsamuel** [comment] 2016-10-28 10:13
Hi @ndro-agus 

I've checked on CSV and MySQL dump:
- All regencies have name (CSV [regencies.csv line 501-514](https://github.com/edwardsamuel/Wilayah-Administratif-Indonesia/blob/c101ef27d1e2b9419523585927a5edf9e5f2b1ad/csv/regencies.csv#L501-L514) and MySQL dump line 637-650).
- All districts have its own regency (CSV [districts.csv line 6956-7093](https://github.com/edwardsamuel/Wilayah-Administratif-Indonesia/blob/c101ef27d1e2b9419523585927a5edf9e5f2b1ad/csv/districts.csv#L6956-L7093) and MySQL dump line 7754-7893).

Did you see any errors while you were importing the dump?

**Comment by ndro-agus** [comment] 2016-10-28 15:00
no, there is no error, but some data is missing,
there are some district have regency id, but the id was not exists in regency table.

**Comment by edwardsamuel** [comment] 2016-10-28 16:07
I can't reproduce the issue and the dump looks good to me.
Could you please get a list of districts that have a non-existing regency to here and the query to get the list?
If it is possible, could you try to reimport the database?

**Comment by ndro-agus** [comment] 2016-10-31 23:44
well, I have fetched data for the rest regency from Central Agency on Statistics (BPS) - MFD and MBS Update (http://mfdonline.bps.go.id/).

regency ID from 9419 to 9471,
Check DISTINCT regency ID from district, and compare with DISTINCT regency ID from regency.

you will see the differences.

**Comment by edwardsamuel** [comment] 2016-11-13 16:51
Most probably, there was an issue while importing [MySQL dump](https://github.com/edwardsamuel/Wilayah-Administratif-Indonesia/blob/c101ef27d1e2b9419523585927a5edf9e5f2b1ad/mysql/indonesia.sql) line 637-650, which contains the missing regency's name. Since it is not reproducible, I will close this issue. Feel free to re-open this issue if anyone faces missing regency's name issue again.

**Closed as completed by edwardsamuel** 2016-11-13 16:51 UTC
